files = {
    "reportsFolderPath": "\\\casagnasfile1\\redirections$\\Maxime.Lepage\\Desktop\\PyDL\\s6v3\\Rapports\\",
    "fileExtension": ".pbix",
    "templatePath": "\\\casagnasfile1\\redirections$\\Maxime.Lepage\\Desktop\\PyDL\\s6v3\\Rapports\\template.pbix",
}
pattern = {
    "server": "casagzsql5",
    "database": "COA",
}
authorize_non_related_report_creation = False
force_use_config_file_envs = False
get_only_used_data_input = True
environments = [
    {
        "name" : "CARB_SUPRV_CLIENT",
        "server" : "casagzsqld2",
        "database" : "PTN_CARB_SUPRV_CLIENT",
        "storedProcedure" : "GetPatternData",
        "storedProcedureServer" : "casagzsqld2",
        "storedProcedureDatabase" : "PTN_CARB_SUPRV_CLIENT",
        "load" : True,
    },
    {
        "name" : "CARB_SUPRV_PROD",
        "server" : "coa_sql_p1",
        "database" : "PTN_CARB_SUPRV",
        "storedProcedure" : "GetPatternData",
        "storedProcedureServer" : "coa_sql_p1",
        "storedProcedureDatabase" : "PTN_CARB_SUPRV",
        "load" : True,
    },
    {
        "name" : "CARB_SUPRV_QA",
        "server" : "casagzsqld2",
        "database" : "PTN_CARB_SUPRV",
        "storedProcedure" : "GetPatternData",
        "storedProcedureServer" : "casagzsqld2",
        "storedProcedureDatabase" : "PTN_CARB_SUPRV",
        "load" : True,
    },
    {
        "name" : "CAST_SUPRV_CLIENT",
        "server" : "casagzsqld2",
        "database" : "PTN_CAST_SUPRV_CLIENT",
        "storedProcedure" : "usp_GetpatternData",
        "storedProcedureServer" : "casagzsqld2",
        "storedProcedureDatabase" : "PTN_CAST_SUPRV",
        "load" : True,
    },
    {
        "name" : "CAST_SUPRV_DEV",
        "server" : "casagzsqld3",
        "database" : "PTN_CAST_SUPRV",
        "storedProcedure" : "usp_GetpatternData",
        "storedProcedureServer" : "casagzsqld3",
        "storedProcedureDatabase" : "PTN_CAST_SUPRV",
        "load" : True,
    },
    {
        "name" : "CAST_SUPRV_PROD",
        "server" : "coa_sql_p1",
        "database" : "PTN_CAST_SUPRV",
        "storedProcedure" : "usp_GetpatternData",
        "storedProcedureServer" : "coa_sql_p1",
        "storedProcedureDatabase" : "PTN_CAST_SUPRV",
        "load" : True,
    },
    {
        "name" : "CAST_SUPRV_QA",
        "server" : "casagzsqld2",
        "database" : "PTN_CAST_SUPRV",
        "storedProcedure" : "usp_GetpatternData",
        "storedProcedureServer" : "casagzsqld2",
        "storedProcedureDatabase" : "PTN_CAST_SUPRV",
        "load" : True,
    },
    {
        "name" : "CUVE_EX",
        "server" : "coa_sql_p1",
        "database" : "COA_E_PATTERNS_CUVE_EX",
        "storedProcedure" : "GetPatternDetectionSpecificPotDataV2",
        "storedProcedureServer" : "casagzsql5",
        "storedProcedureDatabase" : "COA",
        "load" : True,
    },
    {
        "name" : "CUVE_EX_DEV",
        "server" : "casagzsql1",
        "database" : "COA_E_PATTERNS_CUVE_EX_DEV",
        "storedProcedure" : "GetPatternDetectionSpecificPotDataV2_CUVEXDEV",
        "storedProcedureServer" : "casagzsql5",
        "storedProcedureDatabase" : "COA",
        "load" : False,
    },
    {
        "name" : "METAL_SUPRV_PROD",
        "server" : "coa_sql_p1",
        "database" : "PTN_METAL_SUPRV",
        "storedProcedure" : "?",
        "storedProcedureServer" : "?",
        "storedProcedureDatabase" : "?",
        "load" : True,
    },
    {
        "name" : "METAL_SUPRV_QA",
        "server" : "casagzsqld2",
        "database" : "PTN_METAL_SUPRV",
        "storedProcedure" : "?",
        "storedProcedureServer" : "?",
        "storedProcedureDatabase" : "?",
        "load" : True,
    },
    {
        "name" : "PROD",
        "server" : "coa_sql_p1",
        "database" : "COA_E_Patterns",
        "storedProcedure" : "GetPatternDetectionSpecificPotDataV2",
        "storedProcedureServer" : "casagzsql5",
        "storedProcedureDatabase" : "COA",
        "load" : True,
    },
    {
        "name" : "PREPROD",
        "server" : "casagzsql1",
        "database" : "COA_Patterns_PREPROD",
        "storedProcedure" : "GetPatternDetectionSpecificPotDataV2DEV",
        "storedProcedureServer" : "casagzsql5",
        "storedProcedureDatabase" : "COA",
        "load" : True,
    },
    {
        "name" : "PROD_PI",
        "server" : "coa_sql_p1",
        "database" : "COA_E_PATTERNS_PI",
        "storedProcedure" : "GetPatternDetectionSpecificPotDataV2",
        "storedProcedureServer" : "?",
        "storedProcedureDatabase" : "?",
        "load" : True,
    },
    {
        "name" : "REDU_GTC_PROD",
        "server" : "coa_sql_p1",
        "database" : "PTN_REDU_GTC",
        "storedProcedure" : "usp_GetGTCPatternData",
        "storedProcedureServer" : "?",
        "storedProcedureDatabase" : "?",
        "load" : True,
    },
    {
        "name" : "REDU_GTC_QA",
        "server" : "casagzsqld2",
        "database" : "PTN_REDU_GTC",
        "storedProcedure" : "usp_GetGTCPatternData",
        "storedProcedureServer" : "?",
        "storedProcedureDatabase" : "?",
        "load" : True,
    },
    {
        "name" : "REDU_GTECH_VIGIE_QA",
        "server" : "casagzsqld2",
        "database" : "PTN_REDU_GTECH_VIGIE",
        "storedProcedure" : "GetPatternData",
        "storedProcedureServer" : "?",
        "storedProcedureDatabase" : "?",
        "load" : True,
    },
    {
        "name" : "REDU_SUPRV_CLIENT",
        "server" : "casagzsqld2",
        "database" : "PTN_REDU_SUPRV_CLIENT",
        "storedProcedure" : "GetPatternDetectionSpecificPotDataV2DEV",
        "storedProcedureServer" : "casagzsql5",
        "storedProcedureDatabase" : "COA",
        "load" : True,
    },
    {
        "name" : "REDU_SUPRV_QA",
        "server" : "casagzsqld2",
        "database" : "PTN_REDU_SUPRV",
        "storedProcedure" : "?",
        "storedProcedureServer" : "?",
        "storedProcedureDatabase" : "?",
        "load" : False,
    },
    {
        "name" : "SED_CHIMIE_PROD",
        "server" : "coa_sql_p1",
        "database" : "PTN_SED_CHIMIE",
        "storedProcedure" : "?",
        "storedProcedureServer" : "?",
        "storedProcedureDatabase" : "?",
        "load" : True,
    },
    {
        "name" : "SED_CHIMIE_QA",
        "server" : "casagzsqld2",
        "database" : "PTN_SED_CHIMIE",
        "storedProcedure" : "?",
        "storedProcedureServer" : "?",
        "storedProcedureDatabase" : "?",
        "load" : True,
    },
    {
        "name" : "TEST",
        "server" : "casagzsqld3",
        "database" : "COA_E_PATTERNS_TEST",
        "storedProcedure" : "?",
        "storedProcedureServer" : "?",
        "storedProcedureDatabase" : "?",
        "load" : False,
    },
]